// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCNrHiNqOYUT_fLkKtLQkftrbFf4u86oU',
    appId: '1:335379546692:web:c9841fdbb85bd0b5a13211',
    messagingSenderId: '335379546692',
    projectId: 'mydiary-8227d',
    authDomain: 'mydiary-8227d.firebaseapp.com',
    storageBucket: 'mydiary-8227d.firebasestorage.app',
    measurementId: 'G-H02WS9K0KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6odrgFvqLRh2MX-ldzCUsnWpIW_VAIAw',
    appId: '1:335379546692:android:2c359a733f8892a7a13211',
    messagingSenderId: '335379546692',
    projectId: 'mydiary-8227d',
    storageBucket: 'mydiary-8227d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARTUqZ54TcuUKaShsqu7XP3-ri16Zi0og',
    appId: '1:335379546692:ios:bd5020b0ef39441ca13211',
    messagingSenderId: '335379546692',
    projectId: 'mydiary-8227d',
    storageBucket: 'mydiary-8227d.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARTUqZ54TcuUKaShsqu7XP3-ri16Zi0og',
    appId: '1:335379546692:ios:bd5020b0ef39441ca13211',
    messagingSenderId: '335379546692',
    projectId: 'mydiary-8227d',
    storageBucket: 'mydiary-8227d.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCNrHiNqOYUT_fLkKtLQkftrbFf4u86oU',
    appId: '1:335379546692:web:c64254ba78cc2c1aa13211',
    messagingSenderId: '335379546692',
    projectId: 'mydiary-8227d',
    authDomain: 'mydiary-8227d.firebaseapp.com',
    storageBucket: 'mydiary-8227d.firebasestorage.app',
    measurementId: 'G-HX0HV4SHNB',
  );
}
